In [1]:
import pandas as pd 
from sklearn.linear_model import LinearRegression #Linear Model
from sklearn.tree import DecisionTreeRegressor # Import Decision Tree Classifier
from sklearn.ensemble import RandomForestRegressor #Ensemble Learning Bagging
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import mean_squared_error as MSE #Import scikit-learn metrics module for accuracy calculation 
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import make_scorer, r2_score

In [2]:
data=pd.read_csv(r"Pictures\house price prediction ames city.csv")
data.head()

,Id,MSZoning,Neighborhood,OverallQual,YearBuilt,YearRemodAdd,BsmtQual,HeatingQC,CentralAir,1stFlrSF,GrLivArea,BsmtFullBath,KitchenQual,Fireplaces,GarageType,GarageFinish,GarageCars,PavedDrive,SaleCondition,SalePrice
0,1,RL,CollgCr,7,2003,2003,Gd,Ex,Y,856,1710,1,Gd,0,Attchd,RFn,2,Y,Normal,208500
1,2,RL,Veenker,6,1976,1976,Gd,Ex,Y,1262,1262,0,TA,1,Attchd,RFn,2,Y,Normal,181500
2,3,RL,CollgCr,7,2001,2002,Gd,Ex,Y,920,1786,1,Gd,1,Attchd,RFn,2,Y,Normal,223500
3,4,RL,Crawfor,7,1915,1970,TA,Gd,Y,961,1717,1,Gd,1,Detchd,Unf,3,Y,Abnorml,140000
4,5,RL,NoRidge,8,2000,2000,Gd,Ex,Y,1145,2198,1,Gd,1,Attchd,RFn,3,Y,Normal,250000

### Label Encoding

In [3]:
#make an instance of Label Encoder
label_encoder = preprocessing.LabelEncoder()
data['MSZoning'] = label_encoder.fit_transform(data['MSZoning'])
data['Neighborhood'] = label_encoder.fit_transform(data['Neighborhood'])
data['BsmtQual'] = label_encoder.fit_transform(data['BsmtQual'])
data['HeatingQC'] = label_encoder.fit_transform(data['HeatingQC'])
data['CentralAir'] = label_encoder.fit_transform(data['CentralAir'])
data['KitchenQual'] = label_encoder.fit_transform(data['KitchenQual'])
data['GarageType'] = label_encoder.fit_transform(data['GarageType'])
data['GarageFinish'] = label_encoder.fit_transform(data['GarageFinish'])
data['PavedDrive'] = label_encoder.fit_transform(data['PavedDrive'])
data['SaleCondition'] = label_encoder.fit_transform(data['SaleCondition'])
data.drop('Id', inplace=True, axis=1)
data.head()

,MSZoning,Neighborhood,OverallQual,YearBuilt,YearRemodAdd,BsmtQual,HeatingQC,CentralAir,1stFlrSF,GrLivArea,BsmtFullBath,KitchenQual,Fireplaces,GarageType,GarageFinish,GarageCars,PavedDrive,SaleCondition,SalePrice
0,3,5,7,2003,2003,2,0,1,856,1710,1,2,0,1,1,2,2,4,208500
1,3,24,6,1976,1976,2,0,1,1262,1262,0,3,1,1,1,2,2,4,181500
2,3,5,7,2001,2002,2,0,1,920,1786,1,2,1,1,1,2,2,4,223500
3,3,6,7,1915,1970,3,2,1,961,1717,1,2,1,5,2,3,2,0,140000
4,3,15,8,2000,2000,2,0,1,1145,2198,1,2,1,1,1,3,2,4,250000

In [4]:
X = data.drop('SalePrice', axis=1)
y = data.SalePrice
print('Shape of X = ',X.shape)
print('Shape of y = ',y.shape)

Shape of X =  (1460, 18)
Shape of y =  (1460,)

In [5]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=1)

### Scaling the variables with normalization

In [6]:
mmc = MinMaxScaler()
mmc.fit(X_train)
X_train=mmc.transform(X_train)
X_test=mmc.transform(X_test)

### Linear Regression

In [7]:
# Train and test Linear Regression 
regrlr = LinearRegression()
regrlr.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = regrlr.predict(X_test)
r_lr= r2_score(y_test,y_pred)
print('R2 Score of Linear Regression')
print(r_lr)

R2 Score of Linear Regression
0.8529873943748133

### Decision Tree

In [8]:
# Train and test Decision Tree 
clf = DecisionTreeRegressor(random_state = 0) 
clf = clf.fit(X_train,y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
r_dt= r2_score(y_test,y_pred)
print('R2 Score of Decision Tree')
print(r_dt)

R2 Score of Decision Tree
0.8347011717023565

### Random Forest

In [9]:
# Train and test Random Forest 
clf_rf = RandomForestRegressor(random_state=0)
clf_rf = clf_rf.fit(X_train,y_train)
#Predict the response for test dataset
y_pred = clf_rf.predict(X_test)
r_rf= r2_score(y_test,y_pred)
print('R2 Score of Random Forest')
print(r_rf)

R2 Score of Random Forest
0.9059615993889173

### Extreme Gradient Boosting

In [10]:
# Train and test Extreme Gradient Boosting
clf_xgb = XGBRegressor()
clf_xgb = clf_xgb.fit(X_train,y_train)
#Predict the response for test dataset
y_pred = clf_xgb.predict(X_test)
r_xgb= r2_score(y_test,y_pred)
print('R2 Score of Extreme Gradient Boosting')
print(r_xgb)

R2 Score of Extreme Gradient Boosting
0.9040256388106863

Bagging Approach provided the optimal solution for house price prediction problem statement.